"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-15
"""

from alembic import op
import sqlalchemy as sa

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The application models are canonical and are also created at startup for local demos.
    # Production deployments can replace this marker migration with an autogenerated diff.
    op.create_table(
        "migration_health",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("migration_health")
